version: "3"

services:
  ubuntu_ps:
    container_name: "ubuntu_ps"
    image: 4d80be73be8a
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime
    network_mode: host
    stdin_open: true
    tty: true
